<?php

namespace Vapi\Types;

enum FallbackInworldVoiceVoiceId: string
{
    case Alex = "Alex";
    case Ashley = "Ashley";
    case Craig = "Craig";
    case Deborah = "Deborah";
    case Dennis = "Dennis";
    case Edward = "Edward";
    case Elizabeth = "Elizabeth";
    case Hades = "Hades";
    case Julia = "Julia";
    case Pixie = "Pixie";
    case Mark = "Mark";
    case Olivia = "Olivia";
    case Priya = "Priya";
    case Ronald = "Ronald";
    case Sarah = "Sarah";
    case Shaun = "Shaun";
    case Theodore = "Theodore";
    case Timothy = "Timothy";
    case Wendy = "Wendy";
    case Dominus = "Dominus";
    case Hana = "Hana";
    case Clive = "Clive";
    case Carter = "Carter";
    case Blake = "Blake";
    case Luna = "Luna";
    case Yichen = "Yichen";
    case Xiaoyin = "Xiaoyin";
    case Xinyi = "Xinyi";
    case Jing = "Jing";
    case Erik = "Erik";
    case Katrien = "Katrien";
    case Lennart = "Lennart";
    case Lore = "Lore";
    case Alain = "Alain";
    case Helene = "Hélène";
    case Mathieu = "Mathieu";
    case Etienne = "Étienne";
    case Johanna = "Johanna";
    case Josef = "Josef";
    case Gianni = "Gianni";
    case Orietta = "Orietta";
    case Asuka = "Asuka";
    case Satoshi = "Satoshi";
    case Hyunwoo = "Hyunwoo";
    case Minji = "Minji";
    case Seojun = "Seojun";
    case Yoona = "Yoona";
    case Szymon = "Szymon";
    case Wojciech = "Wojciech";
    case Heitor = "Heitor";
    case Maite = "Maitê";
    case Diego = "Diego";
    case Lupita = "Lupita";
    case Miguel = "Miguel";
    case Rafael = "Rafael";
    case Svetlana = "Svetlana";
    case Elena = "Elena";
    case Dmitry = "Dmitry";
    case Nikolai = "Nikolai";
    case Riya = "Riya";
    case Manoj = "Manoj";
    case Yael = "Yael";
    case Oren = "Oren";
    case Nour = "Nour";
    case Omar = "Omar";
}
