<?php

namespace Vapi\Types;

use Vapi\Core\Json\JsonSerializableType;
use Vapi\Core\Json\JsonProperty;
use Vapi\Core\Types\Union;

class TransferAssistant extends JsonSerializableType
{
    /**
     * @var ?string $name Optional name for the transfer assistant
     */
    #[JsonProperty('name')]
    public ?string $name;

    /**
     * @var TransferAssistantModel $model Model configuration for the transfer assistant
     */
    #[JsonProperty('model')]
    public TransferAssistantModel $model;

    /**
     * @var ?TransferAssistantVoice $voice These are the options for the transfer assistant's voice.
     */
    #[JsonProperty('voice')]
    public ?TransferAssistantVoice $voice;

    /**
     * @var ?TransferAssistantTranscriber $transcriber These are the options for the transfer assistant's transcriber.
     */
    #[JsonProperty('transcriber')]
    public ?TransferAssistantTranscriber $transcriber;

    /**
     * This is the first message that the transfer assistant will say.
     * This can also be a URL to a custom audio file.
     *
     * If unspecified, assistant will wait for user to speak and use the model to respond once they speak.
     *
     * @var ?string $firstMessage
     */
    #[JsonProperty('firstMessage')]
    public ?string $firstMessage;

    /**
     * This is the background sound in the transfer assistant call. Default for phone calls is 'office' and default for web calls is 'off'.
     * You can also provide a custom sound by providing a URL to an audio file.
     *
     * @var (
     *    value-of<TransferAssistantBackgroundSoundZero>
     *   |string
     * )|null $backgroundSound
     */
    #[JsonProperty('backgroundSound'), Union('string', 'null')]
    public string|null $backgroundSound;

    /**
     * This is the plan for when the transfer assistant should start talking.
     *
     * You should configure this if the transfer assistant needs different endpointing behavior than the base assistant.
     *
     * If this is not set, the transfer assistant will inherit the start speaking plan from the base assistant.
     *
     * @var ?StartSpeakingPlan $startSpeakingPlan
     */
    #[JsonProperty('startSpeakingPlan')]
    public ?StartSpeakingPlan $startSpeakingPlan;

    /**
     * This is the mode for the first message. Default is 'assistant-speaks-first'.
     *
     * Use:
     * - 'assistant-speaks-first' to have the assistant speak first.
     * - 'assistant-waits-for-user' to have the assistant wait for the user to speak first.
     * - 'assistant-speaks-first-with-model-generated-message' to have the assistant speak first with a message generated by the model based on the conversation state.
     *
     * @default 'assistant-speaks-first'
     *
     * @var ?value-of<TransferAssistantFirstMessageMode> $firstMessageMode
     */
    #[JsonProperty('firstMessageMode')]
    public ?string $firstMessageMode;

    /**
     * This is the maximum duration in seconds for the transfer assistant conversation.
     * After this time, the transfer will be cancelled automatically.
     * @default 120
     *
     * @var ?float $maxDurationSeconds
     */
    #[JsonProperty('maxDurationSeconds')]
    public ?float $maxDurationSeconds;

    /**
     * This enables filtering of noise and background speech while the user is talking.
     *
     * Features:
     * - Smart denoising using Krisp
     * - Fourier denoising
     *
     * Smart denoising can be combined with or used independently of Fourier denoising.
     *
     * Order of precedence:
     * - Smart denoising
     * - Fourier denoising
     *
     * @var ?BackgroundSpeechDenoisingPlan $backgroundSpeechDenoisingPlan
     */
    #[JsonProperty('backgroundSpeechDenoisingPlan')]
    public ?BackgroundSpeechDenoisingPlan $backgroundSpeechDenoisingPlan;

    /**
     * This is the number of seconds of silence to wait before ending the call. Defaults to 30.
     *
     * @default 30
     *
     * @var ?float $silenceTimeoutSeconds
     */
    #[JsonProperty('silenceTimeoutSeconds')]
    public ?float $silenceTimeoutSeconds;

    /**
     * @param array{
     *   model: TransferAssistantModel,
     *   name?: ?string,
     *   voice?: ?TransferAssistantVoice,
     *   transcriber?: ?TransferAssistantTranscriber,
     *   firstMessage?: ?string,
     *   backgroundSound?: (
     *    value-of<TransferAssistantBackgroundSoundZero>
     *   |string
     * )|null,
     *   startSpeakingPlan?: ?StartSpeakingPlan,
     *   firstMessageMode?: ?value-of<TransferAssistantFirstMessageMode>,
     *   maxDurationSeconds?: ?float,
     *   backgroundSpeechDenoisingPlan?: ?BackgroundSpeechDenoisingPlan,
     *   silenceTimeoutSeconds?: ?float,
     * } $values
     */
    public function __construct(
        array $values,
    ) {
        $this->name = $values['name'] ?? null;
        $this->model = $values['model'];
        $this->voice = $values['voice'] ?? null;
        $this->transcriber = $values['transcriber'] ?? null;
        $this->firstMessage = $values['firstMessage'] ?? null;
        $this->backgroundSound = $values['backgroundSound'] ?? null;
        $this->startSpeakingPlan = $values['startSpeakingPlan'] ?? null;
        $this->firstMessageMode = $values['firstMessageMode'] ?? null;
        $this->maxDurationSeconds = $values['maxDurationSeconds'] ?? null;
        $this->backgroundSpeechDenoisingPlan = $values['backgroundSpeechDenoisingPlan'] ?? null;
        $this->silenceTimeoutSeconds = $values['silenceTimeoutSeconds'] ?? null;
    }

    /**
     * @return string
     */
    public function __toString(): string
    {
        return $this->toJson();
    }
}
