<?php

namespace Vapi\Types;

use Vapi\Core\Json\JsonSerializableType;
use Vapi\Core\Json\JsonProperty;

class TransferAssistant extends JsonSerializableType
{
    /**
     * @var ?string $name Optional name for the transfer assistant
     */
    #[JsonProperty('name')]
    public ?string $name;

    /**
     * @var TransferAssistantModel $model Model configuration for the transfer assistant
     */
    #[JsonProperty('model')]
    public TransferAssistantModel $model;

    /**
     * This is the first message that the transfer assistant will say.
     * This can also be a URL to a custom audio file.
     *
     * If unspecified, assistant will wait for user to speak and use the model to respond once they speak.
     *
     * @var ?string $firstMessage
     */
    #[JsonProperty('firstMessage')]
    public ?string $firstMessage;

    /**
     * This is the mode for the first message. Default is 'assistant-speaks-first'.
     *
     * Use:
     * - 'assistant-speaks-first' to have the assistant speak first.
     * - 'assistant-waits-for-user' to have the assistant wait for the user to speak first.
     * - 'assistant-speaks-first-with-model-generated-message' to have the assistant speak first with a message generated by the model based on the conversation state.
     *
     * @default 'assistant-speaks-first'
     *
     * @var ?value-of<TransferAssistantFirstMessageMode> $firstMessageMode
     */
    #[JsonProperty('firstMessageMode')]
    public ?string $firstMessageMode;

    /**
     * This is the maximum duration in seconds for the transfer assistant conversation.
     * After this time, the transfer will be cancelled automatically.
     * @default 120
     *
     * @var ?float $maxDurationSeconds
     */
    #[JsonProperty('maxDurationSeconds')]
    public ?float $maxDurationSeconds;

    /**
     * This is the number of seconds of silence to wait before ending the call. Defaults to 30.
     *
     * @default 30
     *
     * @var ?float $silenceTimeoutSeconds
     */
    #[JsonProperty('silenceTimeoutSeconds')]
    public ?float $silenceTimeoutSeconds;

    /**
     * @param array{
     *   model: TransferAssistantModel,
     *   name?: ?string,
     *   firstMessage?: ?string,
     *   firstMessageMode?: ?value-of<TransferAssistantFirstMessageMode>,
     *   maxDurationSeconds?: ?float,
     *   silenceTimeoutSeconds?: ?float,
     * } $values
     */
    public function __construct(
        array $values,
    ) {
        $this->name = $values['name'] ?? null;
        $this->model = $values['model'];
        $this->firstMessage = $values['firstMessage'] ?? null;
        $this->firstMessageMode = $values['firstMessageMode'] ?? null;
        $this->maxDurationSeconds = $values['maxDurationSeconds'] ?? null;
        $this->silenceTimeoutSeconds = $values['silenceTimeoutSeconds'] ?? null;
    }

    /**
     * @return string
     */
    public function __toString(): string
    {
        return $this->toJson();
    }
}
